#!/bin/bash
# deploy-to-render.sh
echo "🎯 FREE Render.com Setup for WordPress Core"
echo "=========================================="
echo ""
echo "📋 STEP 1: Sign up at https://render.com"
echo "   - Use GitHub to sign up (free)"
echo ""
echo "📋 STEP 2: Create New Web Service"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Select your wordpress-develop fork"
echo ""
echo "📋 STEP 3: Configure Service (IMPORTANT)"
echo "   - Name: wordpress-core-free-$(date +%s)"
echo "   - Environment: Docker"
echo "   - Dockerfile Path: ./Dockerfile"
echo "   - Plan: Free"
echo "   - Instance Type: Free"
echo "   - Auto-Deploy: ON"
echo ""
echo "📋 STEP 4: Environment Variables"
echo "   Click 'Advanced' and add:"
echo "   - Key: WORDPRESS_DEBUG  Value: false"
echo "   - Key: PHP_MEMORY_LIMIT Value: 128M"
echo ""
echo "📋 STEP 5: Create Service"
echo "   - Click 'Create Web Service'"
echo "   - Wait 2-3 minutes for build"
echo ""
echo "📋 STEP 6: Get Deploy Hook"
echo "   - After service is created, go to Settings"
echo "   - Find 'Manual Deploy Hook'"
echo "   - Copy the URL"
echo ""
echo "📋 STEP 7: Add to GitHub Secrets"
echo "   GitHub Repo → Settings → Secrets → Actions"
echo "   Add: RENDER_DEPLOY_HOOK = [your hook URL]"
echo ""
echo "✅ Done! Your WordPress Core is now on Render.com FREE!"
echo ""
echo "🌐 Your site will be at: https://[service-name].onrender.com"
